#!/usr/bin/env python3
"""Generate the falcon-sensor tray icons.

    nix shell --impure --expr 'with import <nixpkgs> {}; python3.withPackages (ps: [ ps.fonttools ])' \
      --command python3 render-icons.py "$(nix build --no-link --print-out-paths nixpkgs#font-awesome)/share/fonts/opentype/Font Awesome 7 Free-Solid-900.otf"

The mark is Font Awesome Free's `feather-pointed`, extracted from the font as an
SVG path. ATTRIBUTION IS REQUIRED: Font Awesome Free icons are CC BY 4.0
(https://fontawesome.com/license/free).

Why a stock glyph and not a drawing of our own: this started as a hand-drawn
falcon head and it did not survive 22px. Five rounds established that a hooked
beak, a brow ridge and a malar stripe all turn to mush at tray size, and that a
wings-out flight silhouette collapses into a cross. A professionally drawn glyph
is built for small sizes; a hand-rolled bezier guess is not.

Layout: the feather takes the upper-left and the state badge takes the
lower-right, so the two cannot overlap however the tray host scales the icon.
Colour AND glyph both change per state -- the state must never depend on being
able to tell green from amber. Colours are the Astros palette's semantic set
(../../common/astros-theme.json).

Icon names must match ICONS in the flake's tools/falcon-sensor-tray.py.
"""
import os
import sys

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

GLYPH = "feather-pointed"
ATTRIB = ("Mark: Font Awesome Free 7 `feather-pointed`, CC BY 4.0 "
          "(https://fontawesome.com/license/free). Generated by render-icons.py.")

# Feather box, and where the badge sits. SPAN < 22 leaves the lower-right free.
SPAN, OX, OY = 15.4, 0.6, 0.4
BADGE_X, BADGE_Y, BADGE_R = 16.2, 16.2, 4.3
DARK = "#0b1220"

STATES = {
    "protected": ("#3FA96B", '<path d="M13.6 16.4 15.4 18.2 18.8 14.6"/>'),
    "degraded": ("#F5B335", '<path d="M16.2 13.4 V16.6"/><path d="M16.2 18.7 V18.8"/>'),
    "inactive": ("#EF4D5E", '<path d="M13.9 14.1 18.5 18.7"/><path d="M18.5 14.1 13.9 18.7"/>'),
    "unknown": ("#6E8CB0", '<path d="M13.7 16.4 H18.7"/>'),
}


def main(font_path, out_dir):
    font = TTFont(font_path, fontNumber=0)
    glyphs = font.getGlyphSet()
    if GLYPH not in glyphs:
        sys.exit(f"{GLYPH} not in {font_path}")

    bounds = BoundsPen(glyphs)
    glyphs[GLYPH].draw(bounds)
    x0, y0, x1, y1 = bounds.bounds
    width, height = x1 - x0, y1 - y0

    pen = SVGPathPen(glyphs)
    glyphs[GLYPH].draw(pen)
    path = pen.getCommands()

    # Font space is Y-up, SVG is Y-down, hence the negative Y scale.
    scale = SPAN / max(width, height)
    tx = OX - x0 * scale + (SPAN - width * scale) / 2
    ty = OY + height * scale + y0 * scale + (SPAN - height * scale) / 2

    for state, (colour, glyph) in STATES.items():
        target = os.path.join(out_dir, f"falcon-sensor-{state}.svg")
        with open(target, "w") as handle:
            handle.write(
                f'<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 22 22">\n'
                f"  <!-- {ATTRIB} -->\n"
                f'  <g transform="translate({tx:.3f} {ty:.3f}) scale({scale:.5f} {-scale:.5f})">\n'
                f'    <path d="{path}" fill="{colour}"/>\n'
                f"  </g>\n"
                f'  <circle cx="{BADGE_X}" cy="{BADGE_Y}" r="{BADGE_R + 1.0}" fill="{DARK}"/>\n'
                f'  <circle cx="{BADGE_X}" cy="{BADGE_Y}" r="{BADGE_R}" fill="{colour}"/>\n'
                f'  <g fill="none" stroke="{DARK}" stroke-width="1.7" stroke-linecap="round"'
                f' stroke-linejoin="round">{glyph}</g>\n'
                f"</svg>\n"
            )
        print(f"wrote {target}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    main(sys.argv[1], os.path.dirname(os.path.abspath(__file__)))
