#!/usr/bin/env python3
"""Generate the falcon-sensor tray icons.

    nix shell --impure --expr 'with import <nixpkgs> {}; python3.withPackages (ps: [ ps.fonttools ])' \
      --command python3 render-icons.py "$(nix build --no-link --print-out-paths nixpkgs#font-awesome)/share/fonts/opentype/Font Awesome 7 Free-Solid-900.otf"

The mark is Font Awesome Free's `crow`, extracted from the font as an SVG path.
Swapping GLYPH to `feather-pointed` or `dove` also works; those were the other
two that stayed legible at 22px. `kiwi-bird` does not. ATTRIBUTION IS REQUIRED: Font Awesome Free icons are CC BY 4.0
(https://fontawesome.com/license/free).

Why a stock glyph and not a drawing of our own: this started as a hand-drawn
falcon head and it did not survive 22px. Five rounds established that a hooked
beak, a brow ridge and a malar stripe all turn to mush at tray size, and that a
wings-out flight silhouette collapses into a cross. A professionally drawn glyph
is built for small sizes; a hand-rolled bezier guess is not.

Layout: ONE MARK, near-full bleed, state carried by COLOUR ALONE. Colours are
the Astros palette's semantic set (../../common/astros-theme.json).

An earlier version badged a state glyph (tick / bang / cross / dash) into the
lower-right corner. It was removed: the badge cost about 40% of a 22px canvas
and left the bird too small to recognise, in order to repeat what the colour
already said.

TRADE-OFF ACCEPTED: upstream badges a glyph precisely so that state does not
depend on distinguishing green from amber, and green/amber is the hardest pair
for the common red-green colour deficiencies -- which is also the
protected-vs-degraded distinction, the one that matters most here. If that ever
bites, the fix is NOT to re-add a badge but to use a mark that differs in SHAPE
per state: MDI's shield-check / shield-alert / shield-off / shield-outline family
is drawn for exactly this and stays crisp at 22px.

Icon names must match ICONS in the flake's tools/falcon-sensor-tray.py.
"""
import os
import sys

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

GLYPH = "crow"
ATTRIB = ("Mark: Font Awesome Free 7 `crow`, CC BY 4.0 "
          "(https://fontawesome.com/license/free). Generated by render-icons.py.")

# Near-full bleed. The mark gets the whole canvas; state is colour alone.
SPAN = 20.6

STATES = {
    "protected": "#3FA96B",
    "degraded": "#F5B335",
    "inactive": "#EF4D5E",
    "unknown": "#6E8CB0",
}


def main(font_path, out_dir):
    font = TTFont(font_path, fontNumber=0)
    glyphs = font.getGlyphSet()
    if GLYPH not in glyphs:
        sys.exit(f"{GLYPH} not in {font_path}")

    bounds = BoundsPen(glyphs)
    glyphs[GLYPH].draw(bounds)
    x0, y0, x1, y1 = bounds.bounds
    width, height = x1 - x0, y1 - y0

    pen = SVGPathPen(glyphs)
    glyphs[GLYPH].draw(pen)
    path = pen.getCommands()

    # Font space is Y-up, SVG is Y-down, hence the negative Y scale.
    scale = SPAN / max(width, height)
    tx = (22 - width * scale) / 2 - x0 * scale
    ty = (22 + height * scale) / 2 + y0 * scale

    for state, colour in STATES.items():
        target = os.path.join(out_dir, f"falcon-sensor-{state}.svg")
        with open(target, "w") as handle:
            handle.write(
                f'<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 22 22">\n'
                f"  <!-- {ATTRIB} -->\n"
                f'  <g transform="translate({tx:.3f} {ty:.3f}) scale({scale:.5f} {-scale:.5f})">\n'
                f'    <path d="{path}" fill="{colour}"/>\n'
                f"  </g>\n"
                f"</svg>\n"
            )
        print(f"wrote {target}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    main(sys.argv[1], os.path.dirname(os.path.abspath(__file__)))
